name: Pull Request Testing
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build mod jar
        run: |
          chmod +x gradlew 
          ./gradlew deploy

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }} Pull Request
          path: build/tmp/deploy/*.jar
